node("dev-docker-64-slave-1") {
    stage "Container preparation"
    def mycontainer = docker.image('elastest/ci-docker-siblings:latest')
    mycontainer.pull()
    mycontainer.inside("-u 0 -v /var/run/docker.sock:/var/run/docker.sock:rw -v /var/lib/jenkins/caches/durable-task:/var/lib/jenkins/caches/durable-task:rw") {
      git 'https://github.com/elastest/elastest-user-emulator-service.git'
      stage "Build and publish Docker image"

      withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'elastestci-dockerhub', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD']]) {
      sh 'docker login -u "$USERNAME" -p "$PASSWORD"'
      sh 'cd elastestbrowsers/GetVersions && ./build.sh 4 true'
    }
  }
}
