node('docker') {
   stage "Container Prep"
      def mycontainer = docker.image('elastest/ci-docker-siblings:latest')
      mycontainer.pull()
      mycontainer.inside("-u jenkins -v /var/run/docker.sock:/var/run/docker.sock:rw") {
      git 'https://github.com/elastest/elastest-user-emulator-service.git'

      stage "Start ElasTest Platform"
         echo ("Start ElasTest Platform")
         sh "cd e2e-test; ./start_platform.sh"

         ET_ETM_API = sh (
            script: "docker inspect --format=\"{{.NetworkSettings.Networks.elastest_elastest.IPAddress}}\" elastest_etm_1 2> /dev/null",
            returnStdout: true
         ).trim();

         ET_ETM_API="http://"+ET_ETM_API+":8091/"

         echo "ElasTest started in URL ${ET_ETM_API}"

      stage "E2E tests"
         echo ("E2E tests")
         
         withEnv(["ET_ETM_API=${ET_ETM_API}"]) {
            sh 'cd e2e-test; mvn clean test'
         }

         step([$class: 'JUnitResultArchiver', testResults: '**/target/surefire-reports/TEST-*.xml'])

      stage "Stop ElasTest Platform"
         echo ("Start ElasTest Platform")
         sh 'docker run -v /var/run/docker.sock:/var/run/docker.sock --rm elastest/platform stop'
      }
}
